export const ENTITY_LIST_START = "ENTITY_LIST_START";
export const ENTITY_LIST_SUCCESS = "ENTITY_LIST_SUCCESS";
export const ENTITY_LIST_FAIL = "ENTITY_LIST_FAIL";
export const ENTITY_LIST_PROCESS = "ENTITY_LIST_PROCESS";

export const ENTITY_ADD_START = "ENTITY_ADD_START";
export const ENTITY_ADD_SUCCESS = "ENTITY_ADD_SUCCESS";
export const ENTITY_ADD_FAIL = "ENTITY_ADD_FAIL";
export const ENTITY_ADD_PROCESS = "ENTITY_ADD_PROCESS";

export const ENTITY_EDIT_START = "ENTITY_EDIT_START";
export const ENTITY_EDIT_SUCCESS = "ENTITY_EDIT_SUCCESS";
export const ENTITY_EDIT_FAIL = "ENTITY_EDIT_FAIL";
export const ENTITY_EDIT_PROCESS = "ENTITY_EDIT_PROCESS";

export const ENTITY_CHECK_START = "ENTITY_CHECK_START";
export const ENTITY_CHECK_SUCCESS = "ENTITY_CHECK_SUCCESS";
export const ENTITY_CHECK_FAIL = "ENTITY_CHECK_FAIL";
export const ENTITY_CHECK_PROCESS = "ENTITY_CHECK_PROCESS";

export const ENTITY_UPDATE_START = "ENTITY_UPDATE_START";
export const ENTITY_UPDATE_SUCCESS = "ENTITY_UPDATE_SUCCESS";
export const ENTITY_UPDATE_FAIL = "ENTITY_UPDATE_FAIL";
export const ENTITY_UPDATE_PROCESS = "ENTITY_UPDATE_PROCESS";

export const ENTITY_DELETE_START = "ENTITY_DELETE_START";
export const ENTITY_DELETE_SUCCESS = "ENTITY_DELETE_SUCCESS";
export const ENTITY_DELETE_FAIL = "ENTITY_DELETE_FAIL";
export const ENTITY_DELETE_PROCESS = "ENTITY_DELETE_PROCESS";



