export const HOME_TILES_START = "HOME_TILES_START";
export const HOME_TILES_SUCCESS = "HOME_TILES_SUCCESS";
export const HOME_TILES_FAIL = "HOME_TILES_FAIL";
export const HOME_TILES_LIST = "HOME_TILES_LIST";