export const TOP_START = "TOP_START";
export const TOP_SUCCESS = "TOP_SUCCESS";
export const TOP_FAIL = "TOP_FAIL";
export const TOP_PROCESS="TOP_PROCESS";

export const REQUESTLIST_START = "REQUESTLIST_START";
export const REQUESTLIST_SUCCESS = "REQUESTLIST_SUCCESS";
export const REQUESTLIST_FAIL = "REQUESTLIST_FAIL";
export const REQUESTLIST_PROCESS="REQUESTLIST_PROCESS";

export const CASELIST_START = "CASELIST_START";
export const CASELIST_SUCCESS = "CASELIST_SUCCESS";
export const CASELIST_FAIL = "CASELIST_FAIL";
export const CASELIST_PROCESS="CASELIST_PROCESS";