export const ORGANISATION_LIST_START = "ORGANISATION_LIST_START";
export const ORGANISATION_LIST_SUCCESS = "ORGANISATION_LIST_SUCCESS";
export const ORGANISATION_LIST_FAIL = "ORGANISATION_LIST_FAIL";
export const ORGANISATION_LIST_PROCESS = "ORGANISATION_LIST_PROCESS";

export const ORGANISATION_ADD_START = "ORGANISATION_ADD_START";
export const ORGANISATION_ADD_SUCCESS = "ORGANISATION_ADD_SUCCESS";
export const ORGANISATION_ADD_FAIL = "ORGANISATION_ADD_FAIL";
export const ORGANISATION_ADD_PROCESS = "ORGANISATION_ADD_PROCESS";

export const ORGANISATION_EDIT_START = "ORGANISATION_EDIT_START";
export const ORGANISATION_EDIT_SUCCESS = "ORGANISATION_EDIT_SUCCESS";
export const ORGANISATION_EDIT_FAIL = "ORGANISATION_EDIT_FAIL";
export const ORGANISATION_EDIT_PROCESS = "ORGANISATION_EDIT_PROCESS";

export const ORGANISATION_CHECK_START = "ORGANISATION_CHECK_START";
export const ORGANISATION_CHECK_SUCCESS = "ORGANISATION_CHECK_SUCCESS";
export const ORGANISATION_CHECK_FAIL = "ORGANISATION_CHECK_FAIL";
export const ORGANISATION_CHECK_PROCESS = "ORGANISATION_CHECK_PROCESS";

export const ORGANISATION_UPDATE_START = "ORGANISATION_UPDATE_START";
export const ORGANISATION_UPDATE_SUCCESS = "ORGANISATION_UPDATE_SUCCESS";
export const ORGANISATION_UPDATE_FAIL = "ORGANISATION_UPDATE_FAIL";
export const ORGANISATION_UPDATE_PROCESS = "ORGANISATION_UPDATE_PROCESS";

export const ORGANISATION_DELETE_START = "ORGANISATION_DELETE_START";
export const ORGANISATION_DELETE_SUCCESS = "ORGANISATION_DELETE_SUCCESS";
export const ORGANISATION_DELETE_FAIL = "ORGANISATION_DELETE_FAIL";
export const ORGANISATION_DELETE_PROCESS = "ORGANISATION_DELETE_PROCESS";



