export const PROCESS_FORM_LIST_START = "PROCESS_FORM_LIST_START";
export const PROCESS_FORM_LIST_SUCCESS = "PROCESS_FORM_LIST_SUCCESS";
export const PROCESS_FORM_LIST_FAIL = "PROCESS_FORM_LIST_FAIL";
export const PROCESS_FORM_LIST_PROCESS = "PROCESS_FORM_LIST_PROCESS";

export const PROCESS_FORM_ADD_START = "PROCESS_FORM_ADD_START";
export const PROCESS_FORM_ADD_SUCCESS = "PROCESS_FORM_ADD_SUCCESS";
export const PROCESS_FORM_ADD_FAIL = "PROCESS_FORM_ADD_FAIL";
export const PROCESS_FORM_ADD_PROCESS = "PROCESS_FORM_ADD_PROCESS";

export const PROCESS_FORM_EDIT_START = "PROCESS_FORM_EDIT_START";
export const PROCESS_FORM_EDIT_SUCCESS = "PROCESS_FORM_EDIT_SUCCESS";
export const PROCESS_FORM_EDIT_FAIL = "PROCESS_FORM_EDIT_FAIL";
export const PROCESS_FORM_EDIT_PROCESS = "PROCESS_FORM_EDIT_PROCESS";

export const PROCESS_FORM_CHECK_START = "PROCESS_FORM_CHECK_START";
export const PROCESS_FORM_CHECK_SUCCESS = "PROCESS_FORM_CHECK_SUCCESS";
export const PROCESS_FORM_CHECK_FAIL = "PROCESS_FORM_CHECK_FAIL";
export const PROCESS_FORM_CHECK_PROCESS = "PROCESS_FORM_CHECK_PROCESS";

export const PROCESS_FORM_UPDATE_START = "PROCESS_FORM_UPDATE_START";
export const PROCESS_FORM_UPDATE_SUCCESS = "PROCESS_FORM_UPDATE_SUCCESS";
export const PROCESS_FORM_UPDATE_FAIL = "PROCESS_FORM_UPDATE_FAIL";
export const PROCESS_FORM_UPDATE_PROCESS = "PROCESS_FORM_UPDATE_PROCESS";

export const PROCESS_FORM_DELETE_START = "PROCESS_FORM_DELETE_START";
export const PROCESS_FORM_DELETE_SUCCESS = "PROCESS_FORM_DELETE_SUCCESS";
export const PROCESS_FORM_DELETE_FAIL = "PROCESS_FORM_DELETE_FAIL";
export const PROCESS_FORM_DELETE_PROCESS = "PROCESS_FORM_DELETE_PROCESS";