export const PROCESS_LIST_START = "PROCESS_LIST_START";
export const PROCESS_LIST_SUCCESS = "PROCESS_LIST_SUCCESS";
export const PROCESS_LIST_FAIL = "PROCESS_LIST_FAIL";
export const PROCESS_LIST_PROCESS = "PROCESS_LIST_PROCESS";

export const PROCESS_ADD_START = "PROCESS_ADD_START";
export const PROCESS_ADD_SUCCESS = "PROCESS_ADD_SUCCESS";
export const PROCESS_ADD_FAIL = "PROCESS_ADD_FAIL";
export const PROCESS_ADD_PROCESS = "PROCESS_ADD_PROCESS";

export const PROCESS_EDIT_START = "PROCESS_EDIT_START";
export const PROCESS_EDIT_SUCCESS = "PROCESS_EDIT_SUCCESS";
export const PROCESS_EDIT_FAIL = "PROCESS_EDIT_FAIL";
export const PROCESS_EDIT_PROCESS = "PROCESS_EDIT_PROCESS";

export const PROCESS_CHECK_START = "PROCESS_CHECK_START";
export const PROCESS_CHECK_SUCCESS = "PROCESS_CHECK_SUCCESS";
export const PROCESS_CHECK_FAIL = "PROCESS_CHECK_FAIL";
export const PROCESS_CHECK_PROCESS = "PROCESS_CHECK_PROCESS";

export const PROCESS_UPDATE_START = "PROCESS_UPDATE_START";
export const PROCESS_UPDATE_SUCCESS = "PROCESS_UPDATE_SUCCESS";
export const PROCESS_UPDATE_FAIL = "PROCESS_UPDATE_FAIL";
export const PROCESS_UPDATE_PROCESS = "PROCESS_UPDATE_PROCESS";

export const PROCESS_DELETE_START = "PROCESS_DELETE_START";
export const PROCESS_DELETE_SUCCESS = "PROCESS_DELETE_SUCCESS";
export const PROCESS_DELETE_FAIL = "PROCESS_DELETE_FAIL";
export const PROCESS_DELETE_PROCESS = "PROCESS_DELETE_PROCESS";

export const PROCESS_DEPLOY_DELETE_START = "PROCESS_DEPLOY_DELETE_START";
export const PROCESS_DEPLOY_DELETE_SUCCESS = "PROCESS_DEPLOY_DELETE_SUCCESS";
export const PROCESS_DEPLOY_DELETE_FAIL = "PROCESS_DEPLOY_DELETE_FAIL";
export const PROCESS_DEPLOY_DELETE_PROCESS = "PROCESS_DEPLOY_DELETE_PROCESS";

export const PROCESS_DEPLOY_START = "PROCESS_DEPLOY_START";
export const PROCESS_DEPLOY_SUCCESS = "PROCESS_DEPLOY_SUCCESS";
export const PROCESS_DEPLOY_FAIL = "PROCESS_DEPLOY_FAIL";
export const PROCESS_DEPLOY_PROCESS = "PROCESS_DEPLOY_PROCESS";

export const PROCESS_RESET = "PROCESS_RESET";



