export const RULES_LIST_START = "RULES_LIST_START";
export const RULES_LIST_SUCCESS = "RULES_LIST_SUCCESS";
export const RULES_LIST_FAIL = "RULES_LIST_FAIL";
export const RULES_LIST_PROCESS = "RULES_LIST_PROCESS";

export const RULES_ADD_START = "RULES_ADD_START";
export const RULES_ADD_SUCCESS = "RULES_ADD_SUCCESS";
export const RULES_ADD_FAIL = "RULES_ADD_FAIL";
export const RULES_ADD_PROCESS = "RULES_ADD_PROCESS";

export const RULES_EDIT_START = "RULES_EDIT_START";
export const RULES_EDIT_SUCCESS = "RULES_EDIT_SUCCESS";
export const RULES_EDIT_FAIL = "RULES_EDIT_FAIL";
export const RULES_EDIT_PROCESS = "RULES_EDIT_PROCESS";

export const RULES_CHECK_START = "RULES_CHECK_START";
export const RULES_CHECK_SUCCESS = "RULES_CHECK_SUCCESS";
export const RULES_CHECK_FAIL = "RULES_CHECK_FAIL";
export const RULES_CHECK_PROCESS = "RULES_CHECK_PROCESS";

export const RULES_UPDATE_START = "RULES_UPDATE_START";
export const RULES_UPDATE_SUCCESS = "RULES_UPDATE_SUCCESS";
export const RULES_UPDATE_FAIL = "RULES_UPDATE_FAIL";
export const RULES_UPDATE_PROCESS = "RULES_UPDATE_PROCESS";

export const RULES_DELETE_START = "RULES_DELETE_START";
export const RULES_DELETE_SUCCESS = "RULES_DELETE_SUCCESS";
export const RULES_DELETE_FAIL = "RULES_DELETE_FAIL";
export const RULES_DELETE_PROCESS = "RULES_DELETE_PROCESS";