export const SUB_PROCESS_LIST_START = "SUB_PROCESS_LIST_START";
export const SUB_PROCESS_LIST_SUCCESS = "SUB_PROCESS_LIST_SUCCESS";
export const SUB_PROCESS_LIST_FAIL = "SUB_PROCESS_LIST_FAIL";
export const SUB_PROCESS_LIST_PROCESS = "SUB_PROCESS_LIST_PROCESS";

export const SUB_PROCESS_ADD_START = "SUB_PROCESS_ADD_START";
export const SUB_PROCESS_ADD_SUCCESS = "SUB_PROCESS_ADD_SUCCESS";
export const SUB_PROCESS_ADD_FAIL = "SUB_PROCESS_ADD_FAIL";
export const SUB_PROCESS_ADD_PROCESS = "SUB_PROCESS_ADD_PROCESS";

export const SUB_PROCESS_EDIT_START = "SUB_PROCESS_EDIT_START";
export const SUB_PROCESS_EDIT_SUCCESS = "SUB_PROCESS_EDIT_SUCCESS";
export const SUB_PROCESS_EDIT_FAIL = "SUB_PROCESS_EDIT_FAIL";
export const SUB_PROCESS_EDIT_PROCESS = "SUB_PROCESS_EDIT_PROCESS";

export const SUB_PROCESS_CHECK_START = "SUB_PROCESS_CHECK_START";
export const SUB_PROCESS_CHECK_SUCCESS = "SUB_PROCESS_CHECK_SUCCESS";
export const SUB_PROCESS_CHECK_FAIL = "SUB_PROCESS_CHECK_FAIL";
export const SUB_PROCESS_CHECK_PROCESS = "SUB_PROCESS_CHECK_PROCESS";

export const SUB_PROCESS_UPDATE_START = "SUB_PROCESS_UPDATE_START";
export const SUB_PROCESS_UPDATE_SUCCESS = "SUB_PROCESS_UPDATE_SUCCESS";
export const SUB_PROCESS_UPDATE_FAIL = "SUB_PROCESS_UPDATE_FAIL";
export const SUB_PROCESS_UPDATE_PROCESS = "SUB_PROCESS_UPDATE_PROCESS";

export const SUB_PROCESS_DELETE_START = "SUB_PROCESS_DELETE_START";
export const SUB_PROCESS_DELETE_SUCCESS = "SUB_PROCESS_DELETE_SUCCESS";
export const SUB_PROCESS_DELETE_FAIL = "SUB_PROCESS_DELETE_FAIL";
export const SUB_PROCESS_DELETE_PROCESS = "SUB_PROCESS_DELETE_PROCESS";



