export const UNIT_LIST_START = "UNIT_LIST_START";
export const UNIT_LIST_SUCCESS = "UNIT_LIST_SUCCESS";
export const UNIT_LIST_FAIL = "UNIT_LIST_FAIL";
export const UNIT_LIST_PROCESS = "UNIT_LIST_PROCESS";

export const UNIT_ADD_START = "UNIT_ADD_START";
export const UNIT_ADD_SUCCESS = "UNIT_ADD_SUCCESS";
export const UNIT_ADD_FAIL = "UNIT_ADD_FAIL";
export const UNIT_ADD_PROCESS = "UNIT_ADD_PROCESS";

export const UNIT_EDIT_START = "UNIT_EDIT_START";
export const UNIT_EDIT_SUCCESS = "UNIT_EDIT_SUCCESS";
export const UNIT_EDIT_FAIL = "UNIT_EDIT_FAIL";
export const UNIT_EDIT_PROCESS = "UNIT_EDIT_PROCESS";

export const UNIT_CHECK_START = "UNIT_CHECK_START";
export const UNIT_CHECK_SUCCESS = "UNIT_CHECK_SUCCESS";
export const UNIT_CHECK_FAIL = "UNIT_CHECK_FAIL";
export const UNIT_CHECK_PROCESS = "UNIT_CHECK_PROCESS";

export const UNIT_UPDATE_START = "UNIT_UPDATE_START";
export const UNIT_UPDATE_SUCCESS = "UNIT_UPDATE_SUCCESS";
export const UNIT_UPDATE_FAIL = "UNIT_UPDATE_FAIL";
export const UNIT_UPDATE_PROCESS = "UNIT_UPDATE_PROCESS";

export const UNIT_DELETE_START = "UNIT_DELETE_START";
export const UNIT_DELETE_SUCCESS = "UNIT_DELETE_SUCCESS";
export const UNIT_DELETE_FAIL = "UNIT_DELETE_FAIL";
export const UNIT_DELETE_PROCESS = "UNIT_DELETE_PROCESS";



